--usuniecie starych danych jesli istnieja
DROP OWNED BY app CASCADE;
DROP USER IF EXISTS app;
DROP TABLE IF EXISTS vote CASCADE;
DROP TABLE IF EXISTS action CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS leader CASCADE;
DROP TABLE IF EXISTS member CASCADE;